import Board from '@/components/Board'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tic Tac Toe Ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen general-bg flex justify-center items-center'>
        <Board />
      </main>
    </>
  )
}
